kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: react-docker
        image: prakhards98/jenkins-react:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
